routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/master', function () {
    return view('adminlte.master');
});

Route::resource('profil', 'ProfilController')->middleware('auth');

Route::get('/beranda', 
    'PertanyaanController@index')
    //function () {return view('adminlte.blank');})  
    ->middleware('auth');

Route::get('/profiles', function () {
    return view('profil.profil2');
})->middleware('auth');

Route::resource('follow', 'FollowController');
Route ::get('/data-tables',function(){
    return view('data-tabel.create');
});

Route::resource('postingan', 'PertanyaanController');

// Route ::get('/postingan/create', 'PertanyaanController@create');

// Route ::post('/postingan', 'PertanyaanController@store');

// Route ::get('/postingan', 'PertanyaanController@index')->middleware('auth');

// Route ::get('/postingan/{id}', 'PertanyaanController@show');

// Route ::get('/postingan/{id}/edit', 'PertanyaanController@edit');

// Route ::put('/postingan/{id}', 'PertanyaanController@update');

// Route ::delete('/postingan/{id}', 'PertanyaanController@destroy');

app/Profil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profil extends Model
{
    protected $guarded = [];

    protected $table = 'profil';

    public function user(){
        return $this->belongsTo('App\User');
    }

    
}

app/Http/Controllers/ProfilController.php
<?php

namespace App\Http\Controllers;

use App\Profil;
use Illuminate\Http\Request;
use Auth;
use RealRashid\SweetAlert\Facades\Alert;


class ProfilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //return view('home');

        //$pertanyaan = DB::table('pertanyaan')->get();
        //$profil = Profil::all();
        $profil = Profil::where('user_id','<>',Auth::id())->get();
        
        //$user = Auth::user();

        //$profilid = $user->profile;
        //$pertanyaan = $profilid->pertanyaan->profil_id;
        //$pertanyaan = $profilid->pertanyaan;
        //dd($profil);
        return view('profil.profil2', compact('profil'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('profil.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|unique:profil',
        ]);

        //dd($request);

        $profil = Profil::create([
            'nama' => $request["nama"],
            'bio' => $request["bio"],
            'user_id' => Auth::id()
        ]);
        //return redirect('/profil')->with('success', 'Profil berhasil disimpan!');
        Alert::success('Selamat bergabung!', 'Anda telah berhasil daftar!');
        return redirect('/beranda');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Profil  $profil
     * @return \Illuminate\Http\Response
     */
    public function show(Profil $profil)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Profil  $profil
     * @return \Illuminate\Http\Response
     */
    public function edit(Profil $profil)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Profil  $profil
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Profil $profil)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Profil  $profil
     * @return \Illuminate\Http\Response
     */
    public function destroy(Profil $profil)
    {
        //
    }
}

resources/views/profil/create.blade.php
@extends('adminlte.master')

@section('content')
  <div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Profil</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="/profil" method="POST">
        @csrf
      <div class="card-body">
        <div class="form-group">
          <label for="nama">Nama</label>
          <input type="text" class="form-control" name="nama" value="{{ old('nama', Auth::user()->name) }}" id="nama" placeholder="Nama">
          @error('nama')
            <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>

        <div class="form-group">
          <label for="bio">Bio</label>
          <input type="text" class="form-control" name="bio" value="{{ old('bio', '') }}" id="bio" placeholder="Bio">
          @error('isi')a
            <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>

      </div>
      <!-- /.card-body -->

      <div class="card-footer">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
@endsection

resources/views/profil/edit.blade.php
@extends('adminlte.master')

@section('content')
  <div class="card card-primary">
    <div class="card-header">
    <h3 class="card-title">Ubah Pertanyaan {{ $pertanyaan->id}}</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="/pertanyaan/{{ $pertanyaan->id}}" method="POST">
      @csrf
      @method('PUT')
      <div class="card-body">
        <div class="form-group">
          <label for="judul">Judul</label>
          <input type="text" class="form-control" name="judul" value="{{ old('judul', $pertanyaan->judul) }}" id="judul" placeholder="Judul">
          @error('judul')
            <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>

        <div class="form-group">
          <label for="isi">Isi</label>
          <input type="text" class="form-control" name="isi" value="{{ old('isi', $pertanyaan->isi) }}" id="isi" placeholder="Isi">
          @error('isi')
            <div class="alert alert-danger">{{ $message }}</div>
          @enderror
        </div>

      </div>
      <!-- /.card-body -->

      <div class="card-footer">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </form>
  </div>
@endsection

resources/views/profil/index.blade.php
@extends('adminlte.master')

@section('content')
    <div class="mt-3 ml-3">
        <div class="card">
            <div class="card-header">
              <h3 class="card-title">Tabel Pertanyaan</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                @if(session('success'))
                  <div class="alert alert-success">
                      {{ session('success') }}
                  </div>   
                @endif
                <a class="btn btn-primary mb-2" href="{{ route('pertanyaan.create') }}">Buat Pertanyaan</a>
              <table class="table table-bordered">
                <thead>                  
                  <tr>
                    <th style="width: 10px">#</th>
                    <th>Judul</th>
                    <th>Pertanyaan</th>
                    <th style="width: 40px">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  @forelse($pertanyaan as $key => $pertanyaan)
                    <tr>
                        <td>{{$key +1 }} </td>
                        <td>{{$pertanyaan -> judul }} </td>
                        <td>{{$pertanyaan -> isi }} </td>
                        <td style="display: flex;">
                            <a href="{{ route('pertanyaan.show', ['pertanyaan' => $pertanyaan->id])}}" class="btn btn-info btn-sm">Show</a>
                            <a href="/pertanyaan/{{$pertanyaan->id}}/edit" class="btn btn-default btn-sm">Edit</a>
                            <form action="{{ route('pertanyaan.destroy', ['pertanyaan' => $pertanyaan->id])}}" method="post">
                                @csrf
                                @method('DELETE')
                                <input type="submit" value="delete" class="btn btn-danger btn-sm">
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="4" align="center"> Tidak ada pertanyaan</td>
                    </tr>
                  @endforelse
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
    
    </div>
@endsection

resources/views/profil/myprofil.blade.php
<div class="card card-widget widget-user" style="margin-bottom: 0px;">
    <!-- Add the bg color to the header using any of the bg-* classes -->
    <div class="widget-user-header bg-info">
      <h2 class="widget-user-username"><strong>{{Auth::user()->profil->nama}}</strong></h2>
      <p class="widget-user-desc">{{Auth::user()->profil->bio}}</p>
    </div>
    <div class="widget-user-image">
      <img class="img-circle" src="{{ asset('/adminlte/dist/img/user3-128x128.jpg')}}" alt="User Avatar">
    </div>
    <div class="card-footer">
      <div class="row">
        <div class="col-sm-4 border-right">
          <div class="description-block">
            <h5 class="description-header">{{ App\Follow::where('following_id','=',Auth::id())->get()->count()}}</h5>
            <span class="description-text">Following</span>
          </div>
          <!-- /.description-block -->
        </div>
        <!-- /.col -->
        <div class="col-sm-4 border-right">
          <div class="description-block">
            <h5 class="description-header">{{ App\Follow::where('followed_id','=',Auth::id())->get()->count()}}</h5>
            <span class="description-text">Followers</span>
          </div>
          <!-- /.description-block -->
        </div>
        <!-- /.col -->
        <div class="col-sm-4">
          <div class="description-block">
            <h5 class="description-header">ID</h5>
            <span class="description-text">{{Auth::id()}}</span>
          </div>
          <!-- /.description-block -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
  </div>

resources/views/profil/profil2.blade.php
@extends('adminlte.master')

@section('content')
    <div class="mt-3 ml-3 mr-3">
      <div class="row justify-content-start"  id="listProfil" >
        @forelse($profil as $profil)
          <div class="col-4 mt-1">
            <div class="card card-widget widget-user">
              <!-- Add the bg color to the header using any of the bg-* classes -->
              <!--<div class="widget-user-header text-white" style="background: url('{{ asset('/adminlte/dist/img/photo1.png')}}') center center;">-->
              <div class="widget-user-header bg-info">
                <h2 class="widget-user-username"><strong>{{$profil -> nama }}</strong></h2>
                <p class="widget-user-desc">{{$profil -> bio }}</p>
              </div>
              <div class="widget-user-image">
                <img class="img-circle" src="{{ asset('/adminlte/dist/img/avatar5.png')}}" alt="User Avatar">
              </div>
              <div class="card-footer">
                <div class="row">
                  <div class="col-sm-4 border-right">
                    <div class="description-block">
                      <h5 class="description-header">{{ App\Follow::where('following_id','=',$profil->user_id)->get()->count()}}</h5>
                      <span class="description-text">Following</span>
                    </div>
                    <!-- /.description-block -->
                  </div>
                  <!-- /.col -->
                  <div class="col-sm-4">
                    <div class="description-block">
                      <h5 class="description-header">{{ App\Follow::where('followed_id','=',$profil->user_id)->get()->count()}}</h5>
                      <span class="description-text">Followers</span>
                    </div>
                    <!-- /.description-block -->
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-4">
                    <form action="{{ route('follow.store', ['id' => $profil->user_id])}}" class="follow-{{ $profil->user_id }}" method="POST">
                      @csrf
                      <input type="submit" value="Follow" class="btn btn-primary btn-sm"></form>
                  </div>
                </div>
                <!-- /.row -->
              </div>
            </div>
          </div>
        @empty
            <p align="center"> Profil tidak ditemukan</p>
        @endforelse

      </div>
    </div>

@endsection

resources/views/profil/show.blade.php
@extends('adminlte.master')

@section('content')
    <div class="mt-3 ml-3">
        <h4>{{$pertanyaan->judul}}</h4>
        <p>{{$pertanyaan->isi}}</p>
        <p> Penanya : {{ $pertanyaan->penanya->nama_lengkap }} </p>
    </div>
@endsection